version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Задает пользователя
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Задает пароль для пользователя
      POSTGRES_DB: ${POSTGRES_DB} # Создает базу данных с заданным именем 
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
